# Generated by Django 5.1.7 on 2025-06-30 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='HS код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='Подкатегория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'HS код',
                'verbose_name_plural': 'HS коды',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Всего позиций')),
                ('processed_items', models.PositiveIntegerField(default=0, verbose_name='Обработано позиций')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача обработки',
                'verbose_name_plural': 'Задачи обработки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('row_number', models.PositiveIntegerField(verbose_name='Номер строки')),
                ('original_description', models.TextField(verbose_name='Исходное описание')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Уровень доверия')),
                ('alternatives', models.JSONField(default=list, verbose_name='Альтернативные коды')),
                ('ai_reasoning', models.TextField(blank=True, verbose_name='Обоснование AI')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processed', 'Обработано'), ('confirmed', 'Подтверждено'), ('needs_review', 'Требует проверки'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('user_comment', models.TextField(blank=True, verbose_name='Комментарий пользователя')),
                ('final_hs_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_items', to='core.hscode', verbose_name='Финальный HS код')),
                ('suggested_hs_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hscode', verbose_name='Предложенный HS код')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.processingtask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Позиция товара',
                'verbose_name_plural': 'Позиции товаров',
                'ordering': ['task', 'row_number'],
                'unique_together': {('task', 'row_number')},
            },
        ),
    ]
